# Generated by Django 4.2.29 on 2026-04-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, default='Московская область, г. Сергиев Посад', max_length=200, verbose_name='Адрес питомника'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='hello@tvoysad.ru', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+7 (999) 123-45-67', max_length=50, verbose_name='Телефон (основной)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_delivery',
            field=models.CharField(blank=True, default='+7 (999) 987-65-43', max_length=50, verbose_name='Телефон (доставка)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='schedule',
            field=models.CharField(default='Ежедневно: 9:00–20:00', max_length=100, verbose_name='График работы'),
        ),
    ]
