# Generated by Django 4.2.29 on 2026-04-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_sitesettings_address_sitesettings_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='courier_price',
            field=models.PositiveIntegerField(default=500, verbose_name='Цена курьерской доставки (₽)'),
        ),
    ]
