# Generated by Django 5.2.10 on 2026-05-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_sitesettings_courier_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tg_admin_chat_id',
            field=models.CharField(blank=True, help_text='ID чата/пользователя для уведомлений о заказах. Узнать можно через @userinfobot.', max_length=50, verbose_name='Telegram Chat ID администратора'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_bot_token',
            field=models.CharField(blank=True, help_text='Токен бота из @BotFather, например: 123456789:AAF...', max_length=200, verbose_name='Telegram Bot Token'),
        ),
    ]
