# Generated by Django 5.2.10 on 2026-05-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_sitesettings_telegram_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tg_proxy_url',
            field=models.CharField(blank=True, help_text='HTTP/HTTPS прокси, если сервер не может подключиться к Telegram напрямую. Формат: http://user:pass@host:port или socks5://host:port', max_length=300, verbose_name='Прокси для Telegram (необязательно)'),
        ),
    ]
