# Generated by Django 4.2.29 on 2026-04-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='source',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('web', 'Веб')], db_index=True, default='web', max_length=20, verbose_name='Источник'),
        ),
    ]
