# Generated by Django 4.2.29 on 2026-04-04 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('language_code', models.CharField(blank=True, max_length=10, verbose_name='Язык')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('allows_write_to_pm', models.BooleanField(default=False, verbose_name='Разрешил ЛС')),
                ('photo_url', models.URLField(blank=True, verbose_name='Фото')),
                ('platform', models.CharField(blank=True, max_length=50, verbose_name='Платформа')),
                ('tg_version', models.CharField(blank=True, max_length=20, verbose_name='Версия TG')),
                ('client_platform', models.CharField(blank=True, max_length=100, verbose_name='Клиент')),
                ('visits_count', models.PositiveIntegerField(default=0, verbose_name='Визитов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Первый визит')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Последний визит')),
            ],
            options={
                'verbose_name': 'Telegram пользователь',
                'verbose_name_plural': 'Telegram пользователи',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='TelegramVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=500, verbose_name='Страница')),
                ('platform', models.CharField(blank=True, max_length=50, verbose_name='Платформа TG')),
                ('screen_width', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ширина экрана')),
                ('screen_height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Высота экрана')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('theme', models.CharField(blank=True, max_length=10, verbose_name='Тема')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='tg_users.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Визит',
                'verbose_name_plural': 'Визиты',
                'ordering': ['-created_at'],
            },
        ),
    ]
