# Generated by Django 4.2.29 on 2026-04-04 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('error', 'Ошибка'), ('read', 'Прочитано')], db_index=True, default='sent', max_length=10, verbose_name='Статус')),
                ('error_text', models.CharField(blank=True, max_length=500, verbose_name='Текст ошибки')),
                ('tg_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID в Telegram')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tg_users.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Исходящее сообщение',
                'verbose_name_plural': 'Исходящие сообщения',
                'ordering': ['-sent_at'],
            },
        ),
    ]
